const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const api=require('../ui/monitor-review.js');
const rid='a'.repeat(64),eid='b'.repeat(64),did='c'.repeat(64),now=Date.parse('2026-09-23T12:00:00Z');
function fixture(){
 const record={id:rid,source_id:'test-board',source_record_id:'test-record',source_url:'https://example.org/job',source_publication_date:null,publication_precision:'UNKNOWN',publication_clock:'NO_PUBLICATION_DATE_IN_LIST',source_updated_at:null,first_observed_at:'2026-09-22T10:00:00Z',last_observed_at:'2026-09-23T10:00:00Z',raw_sha256:'d'.repeat(64),canada_relevance:'CANDIDATE_REQUIRES_REVIEW',scope_exclusion:null,backtest_eligible:false,public_alert_allowed:false};
 const event={id:eid,kind:'RECORD_CHANGED',observed_at:record.last_observed_at,record,public_alert_allowed:false,review_required:true};
 const checkpoint={schema_version:1,raw_retention_days:90,historical_backtest_eligible:false,tables:{company_source_state:[{id:'test-board',contract:'e'.repeat(64),last_success:record.last_observed_at}],company_observations:[{id:rid,source_id:'test-board',first_seen:record.first_observed_at,last_seen:record.last_observed_at,fingerprint:'f'.repeat(64),payload:JSON.stringify(record)}],company_observation_events:[{id:eid,source_id:'test-board',observed_at:event.observed_at,kind:event.kind,payload:JSON.stringify(event)}]},runs:[{id:'test-run',finished_at:'2026-09-23T10:01:00Z',sources:[{id:'test-board',status:'OBSERVED'}]}]};
 const register={decisions:[{id:did,project_id:null,company_name:'TEST COMPANY',evidence:[{source_id:'test-board'}],checks:{source_reuse:'UNKNOWN'}}]};return {checkpoint,register};
}
function encoded(c){delete c.checksum;c.checksum=crypto.createHash('sha256').update(api.canonical(c)).digest('hex');return JSON.stringify(c);}
function changeRecord(c,change){for(const o of c.tables.company_observations){const r=JSON.parse(o.payload);change(r);o.payload=JSON.stringify(r);}for(const e of c.tables.company_observation_events){const p=JSON.parse(e.payload);change(p.record);e.payload=JSON.stringify(p);}}
test('read-only projection binds metadata to exact source review, not a name match',async()=>{const {checkpoint:c,register:r}=fixture(),raw=encoded(c),before=JSON.stringify(r),m=await api.parse(raw,r,now);assert.equal(m.items.length,1);assert.equal(m.items[0].company_id,did);assert.equal(m.items[0].qualified,false);assert.equal(m.items[0].public_alert_allowed,false);assert.equal(JSON.stringify(r),before);assert.equal(JSON.stringify(c),raw);});
test('unknown publication is never replaced by observation clock',async()=>{const {checkpoint:c,register:r}=fixture(),m=await api.parse(encoded(c),r,now);assert.equal(m.items[0].source_publication_date,null);assert.equal(m.items[0].first_observed_at,'2026-09-22T10:00:00Z');});
test('checksum corruption fails before rendering',async()=>{const {checkpoint:c,register:r}=fixture();const raw=encoded(c).replace('TEST_SENTINEL','unused');c.runs[0].id='changed';await assert.rejects(()=>api.parse(JSON.stringify(c),r,now),/checksum/);assert.ok(raw);});
test('scope-held metadata is counted but never promoted to actionable row',async()=>{const {checkpoint:c,register:r}=fixture();changeRecord(c,x=>x.scope_exclusion='MILITARY_REVIEW_HOLD');const m=await api.parse(encoded(c),r,now);assert.equal(m.items.length,0);assert.equal(m.counts.scope_held,1);assert.equal(m.counts.total_events,1);});
test('unknown geography is not Canadian activity',async()=>{const {checkpoint:c,register:r}=fixture();changeRecord(c,x=>x.canada_relevance='NOT_ESTABLISHED');const m=await api.parse(encoded(c),r,now);assert.equal(m.items.length,0);assert.equal(m.counts.geography_unconfirmed,1);});
test('ambiguous source bindings are quarantined instead of fuzzy joined',async()=>{const {checkpoint:c,register:r}=fixture();r.decisions.push({...r.decisions[0],id:'9'.repeat(64)});const m=await api.parse(encoded(c),r,now);assert.equal(m.items.length,0);assert.equal(m.counts.unbound,1);});
test('missing register leaves a disclosed binding gap',async()=>{const {checkpoint:c}=fixture(),m=await api.parse(encoded(c),null,now);assert.equal(m.register_available,false);assert.equal(m.counts.unbound,1);});
test('stale source collection not refreshed by page generation',async()=>{const {checkpoint:c,register:r}=fixture(),m=await api.parse(encoded(c),r,now+4*86400000);assert.equal(m.stale,true);assert.equal(m.last_collection_at,'2026-09-23T10:01:00Z');});
test('old changes leave bounded view without deleting historical counts',async()=>{const {checkpoint:c,register:r}=fixture(),m=await api.parse(encoded(c),r,now+40*86400000);assert.equal(m.items.length,0);assert.equal(m.counts.total_events,1);assert.equal(m.counts.older_than_30_days,1);});
test('failed latest source remains visible alongside retained metadata',async()=>{const {checkpoint:c,register:r}=fixture();c.runs[0].sources[0].status='UNVERIFIED_SOURCE_FAILURE';const m=await api.parse(encoded(c),r,now);assert.deepEqual(m.failed_sources,['test-board']);assert.equal(m.items[0].source_status,'UNVERIFIED_SOURCE_FAILURE');});
test('public-alert or historical score flags fail closed',async()=>{for(const key of ['public_alert_allowed','backtest_eligible']){const {checkpoint:c,register:r}=fixture();changeRecord(c,x=>x[key]=true);await assert.rejects(()=>api.parse(encoded(c),r,now));}});
test('unsafe URL or source-body leakage rejected',async()=>{for(const change of [x=>x.source_url='javascript:alert(1)',x=>x.evidence_text='not allowed',x=>x.source_url='https://name:secret@example.org/x']){const {checkpoint:c,register:r}=fixture();changeRecord(c,change);await assert.rejects(()=>api.parse(encoded(c),r,now));}});
test('duplicate events do not inflate the denominator',async()=>{const {checkpoint:c,register:r}=fixture();c.tables.company_observation_events.push({...c.tables.company_observation_events[0]});await assert.rejects(()=>api.parse(encoded(c),r,now),/event identity/);});
test('future source clocks and orphan observations fail',async()=>{const {checkpoint:c,register:r}=fixture();c.tables.company_source_state[0].last_success='2027-01-01T00:00:00Z';await assert.rejects(()=>api.parse(encoded(c),r,now));});
test('invalid normalized publication day fails',async()=>{const {checkpoint:c,register:r}=fixture();changeRecord(c,x=>x.source_publication_date='2026-02-30');await assert.rejects(()=>api.parse(encoded(c),r,now));});
module.exports={fixture,encoded,now};

test('contradicted source reuse withholds the public source link',()=>{assert.equal(api.sourceLinkAllowed({source_reuse:'CONTRADICTED'}),false);assert.equal(api.sourceLinkAllowed({source_reuse:'UNKNOWN'}),true);assert.equal(api.sourceLinkAllowed({source_reuse:'SUPPORTED'}),true);});
